#!/bin/sh
#
#    Battleships PC client with GFX multi-player game support
#    Copyright (C) 2021 Igor Maznitsa
#
#    This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#

BASEDIR=`dirname "$0"`

exec "$BASEDIR"/jre/bin/java -Dsun.rmi.transport.tcp.maxConnectionThreads=0 -XX:+DisableAttachMechanism -Djava.library.path="$BASEDIR" -Xdock:icon="$BASEDIR"/../Resources/appico.png  -jar "$BASEDIR"/battleships-resurrection*.jar
